# Generated by Django 4.1.3 on 2023-09-10 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='PROBABILITY',
            new_name='HIGH_SCHOOL_POINTS',
        ),
    ]
