# Generated by Django 5.0.2 on 2024-07-12 15:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_remove_data_high_school_points_remove_data_lor_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="data",
            name="Age_month",
        ),
        migrations.RemoveField(
            model_name="data",
            name="Age_of_mom",
        ),
        migrations.RemoveField(
            model_name="data",
            name="BMI_of_mom",
        ),
        migrations.RemoveField(
            model_name="data",
            name="Food_group_consumed",
        ),
        migrations.RemoveField(
            model_name="data",
            name="Food_intake_per_day",
        ),
        migrations.RemoveField(
            model_name="data",
            name="Height_in_cm",
        ),
        migrations.RemoveField(
            model_name="data",
            name="Height_of_mom",
        ),
        migrations.RemoveField(
            model_name="data",
            name="Name",
        ),
        migrations.RemoveField(
            model_name="data",
            name="No_of_Children_ever_born",
        ),
        migrations.RemoveField(
            model_name="data",
            name="Sex",
        ),
        migrations.RemoveField(
            model_name="data",
            name="Weight_kg",
        ),
        migrations.RemoveField(
            model_name="data",
            name="Weight_of_mom_in_kg",
        ),
        migrations.RemoveField(
            model_name="data",
            name="malnutrition_status",
        ),
        migrations.RemoveField(
            model_name="data",
            name="mother_status",
        ),
        migrations.AddField(
            model_name="data",
            name="HIGH_SCHOOL_POINTS",
            field=models.FloatField(
                null=True,
                validators=[
                    django.core.validators.MaxValueValidator(21),
                    django.core.validators.MinValueValidator(7),
                ],
            ),
        ),
        migrations.AddField(
            model_name="data",
            name="LOR",
            field=models.FloatField(
                null=True,
                validators=[
                    django.core.validators.MaxValueValidator(5),
                    django.core.validators.MinValueValidator(0),
                ],
            ),
        ),
        migrations.AddField(
            model_name="data",
            name="RCN",
            field=models.PositiveIntegerField(
                choices=[(1, "Has concept note"), (0, "Has no concept note")], null=True
            ),
        ),
        migrations.AddField(
            model_name="data",
            name="SOP",
            field=models.FloatField(
                null=True,
                validators=[
                    django.core.validators.MaxValueValidator(5),
                    django.core.validators.MinValueValidator(0),
                ],
            ),
        ),
        migrations.AddField(
            model_name="data",
            name="STATUS",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="data",
            name="TOEFL",
            field=models.FloatField(
                null=True,
                validators=[
                    django.core.validators.MaxValueValidator(120),
                    django.core.validators.MinValueValidator(0),
                ],
            ),
        ),
        migrations.AddField(
            model_name="data",
            name="UGPA",
            field=models.FloatField(
                null=True,
                validators=[
                    django.core.validators.MaxValueValidator(5),
                    django.core.validators.MinValueValidator(0),
                ],
            ),
        ),
        migrations.AddField(
            model_name="data",
            name="NAME",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
